### ISSUE TITLE
Add `broadcastarray` for lazy broadcasting?

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaArrays/MappedArrays.jl#19]
It might be nice to support lazy broadcasting as well as lazy mapping, so that:
```julia
broadcastarray(+, [1,2,3], 3)
```
would be a lazy version of `broadcast(+, [1,2,3], 3)`.

**Comment by timholy** [comment]
This is now possible using `Base.Broadcast.Broadcasted`.

**Comment by dlfivefifty** [comment]
But it’s not <: AbstractArray. See https://github.com/dlfivefifty/LazyLinearAlgebra.jl/blob/master/src/lazybroadcasting.jl for an implementation that wraps ` Broadcasted ` .
